# Generated by Django 4.2.3 on 2024-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="class_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="answer",
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="card",
            name="question",
            field=models.CharField(max_length=500),
        ),
    ]
